sudo: required

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

language: python

services:
    - docker

before_install:
    - sudo docker-compose up -d
    - pip install selenium

script:
    - python tests_e2e/*.py