sudo: required

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

language: python

services:
    - docker
before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    - geckodriver --version
    - sudo docker-compose up -d
    - sudo apt-get install xvfb
    - pip install selenium
    - pip install pyvirtualdisplay

script:
    - sleep 10
    - python tests_e2e/*.py
    - cat geckodriver.log
